dubbo:
  application:
    name: user-provider
    owner: guohao
  registry:
    address: nacos://192.168.10.250:8848
    group: user-provider
  protocol:
    name: dubbo
    port: 20881
#  metadata-report:
  scan:
    base-packages: com.gh.dubbo

logging:
  config:
    classpath: logback.xml
